export class MonitoringError extends Error {
  constructor(public readonly code:
    | 'INVALID_SOURCE'
    | 'SOURCE_NOT_FOUND'
    | 'COLLECTOR_UNAVAILABLE'
    | 'INVALID_EVIDENCE'
    | 'INVALID_SCORE'
    | 'INVALID_BUDGET'
    | 'INVALID_DIGEST_CONFIG'
    | 'DIGEST_NOT_FOUND'
    | 'BINDING_MISMATCH'
    | 'CONTEXT_UNAVAILABLE'
    | 'SCHEMA_UNSUPPORTED'
    | 'FOLLOWUP_INVALID'
    | 'FOLLOWUP_NOT_FOUND'
    | 'FOLLOWUP_STATE_CONFLICT'
    | 'FOLLOWUP_BINDING_UNAVAILABLE'
    | 'FOLLOWUP_EVIDENCE_MISMATCH'
    | 'FOLLOWUP_APPROVAL_INVALID'
    | 'FOLLOWUP_PRECONDITION_FAILED'
    | 'FOLLOWUP_EXECUTION_FAILED'
    | 'FOLLOWUP_RECEIPT_MISSING'
    | 'FOLLOWUP_VERIFICATION_FAILED'
    | 'FOLLOWUP_RECONCILIATION_REQUIRED'
    | 'FOLLOWUP_ROLLBACK_FAILED'
    | 'FOLLOWUP_QUARANTINED') {
    super(code)
    this.name = 'MonitoringError'
  }
}
